### 登录
POST {{host}}authorities/login
Content-Type: application/json

{
  "username": "test1",
  "password": "123"
}

### 获取当前用户信息
GET {{host}}authorities
Cookie: Authorization={{token}}

### 刷新 token
PUT {{host}}authorities/tokenRefresh

### 退出
PUT {{host}}authorities/logout
