### 1. 新增 friendShipProfile 实体
POST {{host}}friendShipProfiles
Content-Type: application/json;charset=UTF-8

{
  "operatorId": Long,
  "friendId": Long,
  "nickName": String,
  "chatTop": Boolean
}

### 2. 修改 friendShipProfile 实体
PUT {{host}}friendShipProfiles/1
Content-Type: application/json;charset=UTF-8

{
  "name": "test-1",
  "description": "权限描述",
  "type": 1,
  "url": "权限url-adasd",
  "sequence": 100,
  "display": "1",
  "version": 2,
  "authorities": [
    {
      "method": "GET",
      "url": "/api/v1/permissions/{id}"
    }
  ]
}

### 3. 删除 friendShipProfile 实体
DELETE {{host}}friendShipProfiles/1

###4. 查询 friendShipProfile 实体
GET {{host}}friendShipProfiles/1

### 5. 查询 friendShipProfile 实体列表
GET {{host}}friendShipProfiles?page=2&size=1&sorts=id desc
Content-Type: text/plain

