### 1. 新增 group 实体
POST {{host}}groups
Content-Type: application/json;charset=UTF-8

{
  "name": "String",
  "description": "String",
  "avatar": "String"
}

### 2. 修改 group 实体
PUT {{host}}groups/1
Content-Type: application/json;charset=UTF-8

{
  "name": "String",
  "description": "String",
  "avatar": "String"
}

### 3. 删除 group 实体
DELETE {{host}}groups/1

###4. 查询 group 实体
GET {{host}}groups/1

### 5. 查询 group 实体列表
GET {{host}}groups?page=1&size=2
Content-Type: text/plain

