### 用户列表查询
GET {{host}}users
Cookie: Authorization={{token}}

### 用户列表查询（分页）
GET {{host}}users?page=1&size=10
Cookie: Authorization={{token}}

### 用户详情查询
GET {{host}}users/1

### 用户新增
POST {{host}}users
Content-Type: application/json
Cookie: Authorization={{token}}

{
  "blemish": 0,
  "enabled": true,
  "gender": 1,
  "identity": 2,
  "name": "test1",
  "nickName": "test1",
  "password": "123",
  "phone": "19954246098",
  "phoneArea": "86",
  "username": "test1"
}

### 用户修改
PUT {{host}}users/1

### 用户删除
DELETE {{host}}users/1
