spring:
  datasource:
    url: jdbc:postgresql://59.110.34.78:5432/ju?currentSchema=ju
    username: postgres
    password: Xxzs990416
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 5
      initial-size: 3
  data:
    redis:
      database: 0
      port: 6379
      host: 59.110.34.78
      password: Xxzs990416


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: postgresql
  close-conn: true
  offset-as-page-num: true
  auto-dialect: on  #分页插件会自动检测当前的数据库链接，自动选择合适的分页方式
  reasonable: false #分页合理化参数，默认值为 false 。当该参数设置为 true 时， pageNum<=0 时会查询第一页， pageNum>pages （超过总数时），会查询最后一页
  support-methods-arguments: true #支持通过Mapper接口参数传递page参数,默认值为false
  page-size-zero: true #默认值为 false ，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit =0 就会查询出全部的结果（相当于没有执行分页查询，但是返回结果仍然是 Page 类型）

mybatis-plus:
  configuration:
    default-enum-type-handler: cn.wyz.mapper.typeHandler.DefaultEnumTypeHandler