spring:
  datasource:
    url: jdbc:postgresql://59.110.34.78:5432/ju?currentSchema=ju
    username: postgres
    password: Xxzs990416
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 5
      initial-size: 3
  data:
    redis:
      database: 0
      port: 6379
      host: 59.110.34.78
      password: Xxzs990416


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: postgresql
  reasonable: true
  support-methods-arguments: true
  close-conn: true
  offset-as-page-num: true

mybatis-plus:
  configuration:
    default-enum-type-handler: cn.wyz.mapper.typeHandler.DefaultEnumTypeHandler