server:
  port: 8075

spring:
  datasource:
    url: jdbc:postgresql://43.143.236.141:5432/ju?currentSchema=ju
    username: postgres
    password: Xxzs990416
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 5
      initial-size: 3


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: postgresql
  reasonable: true
  support-methods-arguments: true
  close-conn: true
  offset-as-page-num: true